
#define IDS_APP_TITLE			103

#define IDR_MAINFRAME			128
//#define IDD_VOXELRATOR_DIALOG	102
#define IDD_ABOUTBOX			103
#define IDM_ABOUT				104
#define IDM_EXIT				105
#define IDI_APPICON				107
//#define IDI_SMALL				108
#define IDC_VOLUMERAYTRACER		109
#define IDC_MYICON				2
